# Generated by Django 2.2 on 2019-10-19 04:13

import agent.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_pic', models.BooleanField(default=False)),
                ('image_url', models.ImageField(upload_to=agent.models.upload_to_agent_image)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('NOT', 'Prefer not to say')], max_length=150)),
                ('birth_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.CImages')),
            ],
        ),
    ]
