# Generated by Django 2.2 on 2019-10-19 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_auto_20191019_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='images',
        ),
        migrations.AddField(
            model_name='cimages',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.Agent'),
        ),
    ]
