# Generated by Django 2.2 on 2019-10-20 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0001_initial'),
        ('agent', '0003_auto_20191019_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='region',
        ),
        migrations.AddField(
            model_name='agent',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='state.State'),
        ),
    ]
