# Generated by Django 2.2 on 2019-10-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_auto_20191020_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='birth_date',
            field=models.DateTimeField(),
        ),
    ]
