# Generated by Django 2.2 on 2019-10-18 09:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import property.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.PositiveIntegerField(default=0)),
                ('prop_type', models.CharField(choices=[('HOUSE', 'House'), ('FLAT', 'Flat'), ('OTHER', 'Other')], max_length=150)),
                ('bed_room', models.IntegerField(default=0)),
                ('sale_type', models.CharField(choices=[('SALE', 'Sale'), ('RENT', 'Rent')], max_length=150)),
                ('address1', models.CharField(blank=True, max_length=250, null=True)),
                ('address2', models.CharField(blank=True, max_length=250, null=True)),
                ('region', models.CharField(blank=True, max_length=250, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=250, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='place.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='place.Country')),
            ],
            options={
                'verbose_name_plural': 'properties',
            },
        ),
        migrations.CreateModel(
            name='PropImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_image_url', models.ImageField(upload_to=property.models.upload_with_rename)),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Property')),
            ],
        ),
    ]
