# Generated by Django 2.2 on 2019-10-19 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('border', '0002_auto_20191019_1147'),
        ('property', '0003_auto_20191018_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='city',
        ),
        migrations.RemoveField(
            model_name='property',
            name='country',
        ),
        migrations.AddField(
            model_name='property',
            name='c_border',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='border.Border'),
        ),
        migrations.AlterField(
            model_name='property',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='town.Town'),
        ),
    ]
