# Generated by Django 2.2 on 2019-10-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_property_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bath_rooms',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='room',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='square_meter',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
