# Generated by Django 2.2 on 2019-10-20 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0001_initial'),
        ('property', '0006_auto_20191019_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='region',
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='state.State'),
        ),
    ]
