# Generated by Django 2.2 on 2019-10-21 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20191020_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propimage',
            name='prop',
        ),
        migrations.AddField(
            model_name='property',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.PropImage'),
        ),
    ]
