# Generated by Django 2.2 on 2019-10-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20191021_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propimage',
            name='main_image',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
