# Generated by Django 2.2 on 2019-10-19 06:17

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('border', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='border',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
